language: python
sudo: required
dist: trusty

python:
  - 2.7
  - 3.6
cache: pip
virtualenv:
    system_site_package: true
before_install:
 - sudo apt-get update
install:
 - pip install -r requirements.txt
script:
 - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python -m unittest; fi
 - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then python -m unittest; fi
